<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Security\UserVoter' shared autowired service.

return $this->services['AppBundle\Security\UserVoter'] = new \AppBundle\Security\UserVoter();
